"""add chat_sessions table for DB-backed session state, cart_reminder_sent on orders

Revision ID: 46038d18e7ba
Revises: fa75a0edd0a2
Create Date: 2026-08-02 17:10:34.780348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '46038d18e7ba'
down_revision: Union[str, None] = 'fa75a0edd0a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('known_name', sa.String(length=120), nullable=True),
    sa.Column('known_phone', sa.String(length=20), nullable=True),
    sa.Column('known_email', sa.String(length=255), nullable=True),
    sa.Column('reservation_draft', sa.JSON(), nullable=True),
    sa.Column('checkout_draft', sa.JSON(), nullable=True),
    sa.Column('feedback_pending', sa.Boolean(), nullable=False, server_default=sa.false()),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.add_column('orders', sa.Column('cart_reminder_sent', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'cart_reminder_sent')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
