"""add pending addon fields to chat_sessions

Revision ID: 5b8a6821bd20
Revises: c7d8e2f1a5b3
Create Date: 2026-08-04 01:02:43.956434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5b8a6821bd20'
down_revision: Union[str, None] = 'c7d8e2f1a5b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('pending_addon_item_id', sa.Integer(), nullable=True))
    op.add_column('chat_sessions', sa.Column('pending_addon_item_name', sa.String(length=120), nullable=True))
    op.add_column('chat_sessions', sa.Column('pending_addon_language', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'pending_addon_language')
    op.drop_column('chat_sessions', 'pending_addon_item_name')
    op.drop_column('chat_sessions', 'pending_addon_item_id')
    # ### end Alembic commands ###
